//! Internal helpers for `otter_codegen`. **Not part of the public API.**
//!
//! Everything here is `#[doc(hidden)]` and exists solely so that generated
//! code (which lives in the user's crate) can call into otter internals.

use std::ffi::c_int;

pub use crate::codec::{CodecError, Decoder, Encoder};
pub use crate::env::{Env, EnvKind};
pub use crate::priv_data::{discard_priv_data, free_priv_data, install_priv_data, PrivData};
#[cfg(feature = "raw")]
pub use crate::priv_data::{old_user_priv_field, user_priv_field};
pub use crate::resource::{register, register_tagged, ResourceFlags};
pub use crate::sys::{
    NifEnv, NifEntry, NifFunc, NifResourceTypeInit, NifTerm, NIF_FUNC_DIRTY_CPU,
    NIF_FUNC_DIRTY_IO, NIF_MAJOR_VERSION, NIF_MIN_ERTS_VERSION, NIF_MINOR_VERSION,
    NIF_VM_VARIANT,
};
pub use crate::term::{Term, TypedTerm};
pub use crate::types::Atom;

/// Value for `NifEntry.options` indicating `sizeof_resource_type_init` is set.
pub const NIF_ENTRY_OPTIONS: u32 = 1;

// ---------------------------------------------------------------------------
// Load callback return codes
// ---------------------------------------------------------------------------
//
// BEAM aborts the library load on any non-zero return from the load callback
// and stringifies the integer into the `{error, {load_failed, "...(N)."}}`
// reason. We assign each failure cause a stable integer so that — even without
// a structured channel back to Erlang — users can read the (N) and identify
// the cause.

/// Load succeeded — register the NIF library.
pub const LOAD_OK: c_int = 0;

/// User load callback returned `false`.
pub const LOAD_FAILED_USER_FALSE: c_int = 1;

/// User load callback panicked (caught at the FFI boundary).
pub const LOAD_FAILED_PANIC: c_int = 2;

/// `Decoder::decode` rejected the `load_info` term — the type the user
/// declared for the second parameter of their load callback did not match
/// the actual term passed to `erlang:load_nif(Path, LoadInfo)`.
pub const LOAD_FAILED_DECODE: c_int = 3;

/// Metadata for a single NIF function, generated by `#[otter::nif]`.
pub struct NifMeta {
    pub name: &'static [u8],
    pub arity: u32,
    pub raw_fptr: unsafe extern "C" fn(*mut NifEnv, c_int, *const NifTerm) -> NifTerm,
    pub flags: u32,
}

impl NifMeta {
    /// Convert to a [`NifFunc`] for inclusion in a `NifEntry`.
    pub fn to_nif_func(&self) -> NifFunc {
        NifFunc {
            name: self.name.as_ptr() as *const std::ffi::c_char,
            arity: self.arity as std::ffi::c_uint,
            fptr: self.raw_fptr,
            flags: self.flags as std::ffi::c_uint,
        }
    }
}

/// Construct an [`Env`] from a raw pointer and stack-lifetime marker.
///
/// # Safety
///
/// Same requirements as `Env::new`.
#[inline]
pub unsafe fn new_env<'a>(
    marker: &'a (),
    env: *mut NifEnv,
    kind: EnvKind,
) -> Env<'a> {
    unsafe { Env::new(marker, env, kind) }
}

/// Wrap a raw `NifTerm` into a [`Term`].
#[inline]
pub fn new_raw_term<'a>(env: Env<'a>, term: NifTerm) -> Term<'a> {
    Term::new(env, term)
}

/// Raise `badarg` and return the machine word to hand back from the NIF.
#[inline]
pub fn raise_badarg(env: Env<'_>) -> NifTerm {
    env.make_badarg::<()>().unwrap_err().raw()
}

/// Raise an exception with reason term `reason` and return the machine word.
#[inline]
pub fn raise(env: Env<'_>, reason: NifTerm) -> NifTerm {
    env.raise_exception::<()>(Term::new(env, reason)).unwrap_err().raw()
}
