//! Internal helpers for `otter_codegen`. **Not part of the public API.**
//!
//! Everything here is `#[doc(hidden)]` and exists solely so that generated
//! code (which lives in the user's crate) can call into otter internals.

use std::ffi::c_int;

pub use crate::codec::{CodecError, Decoder, Encoder};
pub use crate::env::{Env, EnvKind};
pub use crate::priv_data::{discard_priv_data, free_priv_data, install_priv_data, PrivData};
#[cfg(feature = "raw")]
pub use crate::priv_data::{old_user_priv_field, user_priv_field};
pub use crate::resource::{register, register_tagged, ResourceFlags};
// enif-ffi consolidates the dirty-scheduler flags: DIRTY_JOB_{CPU,IO}_BOUND
// serve as both the Func.flags values and the schedule_nif flags (same values).
pub use enif_ffi::{
    DIRTY_JOB_CPU_BOUND as NIF_FUNC_DIRTY_CPU,
    DIRTY_JOB_IO_BOUND as NIF_FUNC_DIRTY_IO,
};
// Generated NIF/load/upgrade/unload entry points reference `__codegen::NifEnv`;
// generated registration references `__codegen::NifResourceTypeInit`; the
// generated nif_init entry references the version/variant constants. Keep the
// legacy names as re-exports of the enif_ffi items for now.
pub use enif_ffi::Env as NifEnv;
pub use enif_ffi::Entry as NifEntry;
pub use enif_ffi::ResourceTypeInit as NifResourceTypeInit;
pub use enif_ffi::Term as NifTerm;
pub use enif_ffi::{
    MAJOR_VERSION as NIF_MAJOR_VERSION,
    MINOR_VERSION as NIF_MINOR_VERSION,
    MIN_ERTS_VERSION as NIF_MIN_ERTS_VERSION,
    VM_VARIANT as NIF_VM_VARIANT,
};
pub use crate::term::{Term, TypedTerm};
pub use crate::types::Atom;

/// Value for `enif_ffi::Entry.options` indicating `sizeof_resource_type_init` is set.
pub const NIF_ENTRY_OPTIONS: u32 = 1;

// ---------------------------------------------------------------------------
// Load callback return codes
// ---------------------------------------------------------------------------
//
// BEAM aborts the library load on any non-zero return from the load callback
// and stringifies the integer into the `{error, {load_failed, "...(N)."}}`
// reason. We assign each failure cause a stable integer so that — even without
// a structured channel back to Erlang — users can read the (N) and identify
// the cause.

/// Load succeeded — register the NIF library.
pub const LOAD_OK: c_int = 0;

/// User load callback returned `false`.
pub const LOAD_FAILED_USER_FALSE: c_int = 1;

/// User load callback panicked (caught at the FFI boundary).
pub const LOAD_FAILED_PANIC: c_int = 2;

/// `Decoder::decode` rejected the `load_info` term — the type the user
/// declared for the second parameter of their load callback did not match
/// the actual term passed to `erlang:load_nif(Path, LoadInfo)`.
pub const LOAD_FAILED_DECODE: c_int = 3;

/// Metadata for a single NIF function, generated by `#[otter::nif]`.
pub struct NifMeta {
    pub name: &'static [u8],
    pub arity: u32,
    pub raw_fptr: unsafe extern "C" fn(*mut enif_ffi::Env, c_int, *const enif_ffi::Term) -> enif_ffi::Term,
    pub flags: u32,
}

impl NifMeta {
    /// Convert to a [`enif_ffi::Func`] for inclusion in a `enif_ffi::Entry`.
    pub fn to_nif_func(&self) -> enif_ffi::Func {
        enif_ffi::Func {
            name: self.name.as_ptr() as *const std::ffi::c_char,
            arity: self.arity as std::ffi::c_uint,
            fptr: self.raw_fptr,
            flags: self.flags as std::ffi::c_uint,
        }
    }
}

/// Construct an [`Env`] from a raw pointer and stack-lifetime marker.
///
/// # Safety
///
/// Same requirements as `Env::new`.
#[inline]
pub unsafe fn new_env<'a>(
    marker: &'a (),
    env: *mut enif_ffi::Env,
    kind: EnvKind,
) -> Env<'a> {
    unsafe { Env::new(marker, env, kind) }
}

/// Wrap a raw `enif_ffi::Term` into a [`Term`].
#[inline]
pub fn new_raw_term<'a>(env: Env<'a>, term: enif_ffi::Term) -> Term<'a> {
    Term::new(env, term)
}

/// Raise `badarg` and return the machine word to hand back from the NIF.
#[inline]
pub fn raise_badarg(env: Env<'_>) -> enif_ffi::Term {
    env.make_badarg::<()>().unwrap_err().raw()
}

/// Raise an exception with reason term `reason` and return the machine word.
#[inline]
pub fn raise(env: Env<'_>, reason: enif_ffi::Term) -> enif_ffi::Term {
    env.raise_exception::<()>(Term::new(env, reason)).unwrap_err().raw()
}
